### ISSUE TITLE
Add icons to tag categories

### ISSUE THREAD

**Issue by jdbann** [jdbann/exlibris#49]
To differentiate tags when they're included in a list, icons can be used as a shorthand for the tag's category.

**Comment by KayLotura2** [comment]
Tag Icons Desired (SVG)

* Categories
* Officialness
* Creator
* Compendium
* Link 
* Jam
* Skeletons
* Curses
* Powers

**Comment by mcglincy** [comment]
We can grab placeholders from https://game-icons.net/

**Comment by KayLotura2** [comment]
I have a folder of SVGs and PNGs for these icons
![compendium-or-power](https://user-images.githubusercontent.com/36681220/119516628-c74eb680-bd2b-11eb-9375-659ad824abc0.png)
![compendium](https://user-images.githubusercontent.com/36681220/119516633-c7e74d00-bd2b-11eb-8102-038bd17496ab.png)
![creator-a](https://user-images.githubusercontent.com/36681220/119516635-c87fe380-bd2b-11eb-8418-40a8f02545db.png)
![creator-b](https://user-images.githubusercontent.com/36681220/119516637-c87fe380-bd2b-11eb-9d54-d8090e60547e.png)
![creator-c](https://user-images.githubusercontent.com/36681220/119516639-c9187a00-bd2b-11eb-91cf-9797646e3146.png)
![creator-d](https://user-images.githubusercontent.com/36681220/119516640-c9187a00-bd2b-11eb-9b99-13542f7b5849.png)
![curse-a](https://user-images.githubusercontent.com/36681220/119516641-c9187a00-bd2b-11eb-85a1-8e60fc207409.png)
![curse-b](https://user-images.githubusercontent.com/36681220/119516643-c9b11080-bd2b-11eb-9ced-e4ed0b6e04ef.png)
![curse-c](https://user-images.githubusercontent.com/36681220/119516645-c9b11080-bd2b-11eb-81cd-9562d84d2d9c.png)
![curse-d](https://user-images.githubusercontent.com/36681220/119516646-c9b11080-bd2b-11eb-884f-ad89e8510255.png)
![curse-e](https://user-images.githubusercontent.com/36681220/119516647-ca49a700-bd2b-11eb-93d9-304ce4129a91.png)
![curse-f](https://user-images.githubusercontent.com/36681220/119516648-ca49a700-bd2b-11eb-9295-e3d365ad2d21.png)
![curse-or-power](https://user-images.githubusercontent.com/36681220/119516651-cae23d80-bd2b-11eb-92dc-381f92b9376f.png)
![jam-eye](https://user-images.githubusercontent.com/36681220/119516652-cae23d80-bd2b-11eb-9505-10cf874dc80c.png)
![jam-skull](https://user-images.githubusercontent.com/36681220/119516653-cae23d80-bd2b-11eb-9a05-d33775a798ca.png)
![link-a](https://user-images.githubusercontent.com/36681220/119516654-cae23d80-bd2b-11eb-90e9-eef951dae3f2.png)
![link-b](https://user-images.githubusercontent.com/36681220/119516655-cb7ad400-bd2b-11eb-90c1-2dfd12d616d1.png)
![officialness-a](https://user-images.githubusercontent.com/36681220/119516658-cb7ad400-bd2b-11eb-977d-8e323536fbd7.png)
![officialness-b](https://user-images.githubusercontent.com/36681220/119516661-cb7ad400-bd2b-11eb-96f3-e6e1bcf40a3b.png)
![officialness-d](https://user-images.githubusercontent.com/36681220/119516663-cc136a80-bd2b-11eb-9fc4-ef4498791f27.png)
![officialness-e](https://user-images.githubusercontent.com/36681220/119516665-cc136a80-bd2b-11eb-917c-f14e8a445679.png)
![power-a](https://user-images.githubusercontent.com/36681220/119516666-cc136a80-bd2b-11eb-9375-607330744f93.png)
![power-b](https://user-images.githubusercontent.com/36681220/119516667-cc136a80-bd2b-11eb-86f5-87dda548784b.png)
![power-c](https://user-images.githubusercontent.com/36681220/119516668-ccac0100-bd2b-11eb-9653-9353bb46911d.png)
![skeletons-a](https://user-images.githubusercontent.com/36681220/119516669-ccac0100-bd2b-11eb-85ec-92fff08a4b3d.png)
![skeletons-b](https://user-images.githubusercontent.com/36681220/119516670-ccac0100-bd2b-11eb-9eb9-cb0757d76d4b.png)
