### ISSUE TITLE
Add a default image cover image for entries without art

### ISSUE THREAD

**Issue by jdbann** [jdbann/exlibris#50]
Not sure what to use yet, but worth having something. If we have multiple images, we can randomise this to prevent anything too repetitive - but we don't know how much content will lack art yet.

**Comment by mcglincy** [comment]
As per @dog-quixote: there should be no need for a default image. I can screencap anything that doesn't have a promo image attached to it on a distribution platform.

I think this means we can close this as will-not-fix?

**Comment by mcglincy** [comment]
Will not fix.
