### ISSUE TITLE
Sometimes Create Entry doesn't save

### ISSUE THREAD

**Issue by mcglincy** [jdbann/exlibris#55]
Has happened only ~2 times. Hit some other admin/entries submit bug. Sometimes after I fill in the page and click "Create Entry", it doesn't save and I'm back to the same page, only this time with no cover photo selected and textarea changes gone.

**Comment by jdbann** [comment]
Not sure if the fix I added for #56 will help with this. Are there any particular circumstances which reliably cause this issue? I've not been able to find this problem yet.

**Comment by mcglincy** [comment]
It’s possible it didn’t save because of illegal/missing data and I failed
to notice the displayed error message.

I’ll see if I can repro and verify.

**Comment by jdbann** [comment]
I'm gonna close this as we've now setup Avo and any issues will be substantially different enough to warrant a new issue
